//go:build 386 || arm

package server

import "unsafe"

// Object is still passed directly to legacy C. Keep the 32-bit shared prefix
// byte-for-byte compatible with the original nox_object_t and place Go-only
// handles after it.
var (
	_ = [1]struct{}{}[780-unsafe.Sizeof(Object{})]
	_ = [1]struct{}{}[0-unsafe.Offsetof(Object{}.IDPtr)]
	_ = [1]struct{}{}[4-unsafe.Offsetof(Object{}.TypeInd)]
	_ = [1]struct{}{}[8-unsafe.Offsetof(Object{}.ObjClass)]
	_ = [1]struct{}{}[12-unsafe.Offsetof(Object{}.ObjSubClass)]
	_ = [1]struct{}{}[16-unsafe.Offsetof(Object{}.ObjFlags)]
	_ = [1]struct{}{}[20-unsafe.Offsetof(Object{}.Field5)]
	_ = [1]struct{}{}[28-unsafe.Offsetof(Object{}.Experience)]
	_ = [1]struct{}{}[36-unsafe.Offsetof(Object{}.NetCode)]
	_ = [1]struct{}{}[40-unsafe.Offsetof(Object{}.Extent)]
	_ = [1]struct{}{}[44-unsafe.Offsetof(Object{}.ScriptIDVal)]
	_ = [1]struct{}{}[48-unsafe.Offsetof(Object{}.TeamVal)]
	_ = [1]struct{}{}[56-unsafe.Offsetof(Object{}.PosVec)]
	_ = [1]struct{}{}[64-unsafe.Offsetof(Object{}.NewPos)]
	_ = [1]struct{}{}[72-unsafe.Offsetof(Object{}.PrevPos)]
	_ = [1]struct{}{}[80-unsafe.Offsetof(Object{}.VelVec)]
	_ = [1]struct{}{}[88-unsafe.Offsetof(Object{}.ForceVec)]
	_ = [1]struct{}{}[96-unsafe.Offsetof(Object{}.Pos24)]
	_ = [1]struct{}{}[104-unsafe.Offsetof(Object{}.ZVal)]
	_ = [1]struct{}{}[108-unsafe.Offsetof(Object{}.Field27)]
	_ = [1]struct{}{}[120-unsafe.Offsetof(Object{}.Mass)]
	_ = [1]struct{}{}[124-unsafe.Offsetof(Object{}.Direction1)]
	_ = [1]struct{}{}[126-unsafe.Offsetof(Object{}.Direction2)]
	_ = [1]struct{}{}[128-unsafe.Offsetof(Object{}.Field32)]
	_ = [1]struct{}{}[132-unsafe.Offsetof(Object{}.Field33)]
	_ = [1]struct{}{}[136-unsafe.Offsetof(Object{}.Field34)]
	_ = [1]struct{}{}[140-unsafe.Offsetof(Object{}.Field35)]
	_ = [1]struct{}{}[144-unsafe.Offsetof(Object{}.Field36)]
	_ = [1]struct{}{}[148-unsafe.Offsetof(Object{}.Field37)]
	_ = [1]struct{}{}[152-unsafe.Offsetof(Object{}.Field38)]
	_ = [1]struct{}{}[240-unsafe.Offsetof(PlayerUpdateData{}.MovementFlags)]
	_ = [1]struct{}{}[172-unsafe.Offsetof(Object{}.Shape)]
	_ = [1]struct{}{}[232-unsafe.Offsetof(Object{}.CollideP1)]
	_ = [1]struct{}{}[240-unsafe.Offsetof(Object{}.CollideP2)]
	_ = [1]struct{}{}[248-unsafe.Offsetof(Object{}.Field62)]
	_ = [1]struct{}{}[256-unsafe.Offsetof(Object{}.legacyMapIndex)]
	_ = [1]struct{}{}[340-unsafe.Offsetof(Object{}.Buffs)]
	_ = [1]struct{}{}[344-unsafe.Offsetof(Object{}.BuffsDur)]
	_ = [1]struct{}{}[408-unsafe.Offsetof(Object{}.BuffsPower)]
	_ = [1]struct{}{}[444-unsafe.Offsetof(Object{}.ObjNext)]
	_ = [1]struct{}{}[452-unsafe.Offsetof(Object{}.DeletedNext)]
	_ = [1]struct{}{}[456-unsafe.Offsetof(Object{}.DeletedAt)]
	_ = [1]struct{}{}[492-unsafe.Offsetof(Object{}.InvHolder)]
	_ = [1]struct{}{}[496-unsafe.Offsetof(Object{}.InvNextItem)]
	_ = [1]struct{}{}[504-unsafe.Offsetof(Object{}.InvFirstItem)]
	_ = [1]struct{}{}[508-unsafe.Offsetof(Object{}.ObjOwner)]
	_ = [1]struct{}{}[512-unsafe.Offsetof(Object{}.Field128)]
	_ = [1]struct{}{}[516-unsafe.Offsetof(Object{}.Field129)]
	_ = [1]struct{}{}[520-unsafe.Offsetof(Object{}.Obj130)]
	_ = [1]struct{}{}[536-unsafe.Offsetof(Object{}.Frame134)]
	_ = [1]struct{}{}[556-unsafe.Offsetof(Object{}.HealthData)]
	_ = [1]struct{}{}[716-unsafe.Offsetof(Object{}.Damage)]
	_ = [1]struct{}{}[724-unsafe.Offsetof(Object{}.Death)]
	_ = [1]struct{}{}[560-unsafe.Offsetof(Object{}.Field140)]
	_ = [1]struct{}{}[688-unsafe.Offsetof(Object{}.Init)]
	_ = [1]struct{}{}[692-unsafe.Offsetof(Object{}.InitData)]
	_ = [1]struct{}{}[696-unsafe.Offsetof(Object{}.Collide)]
	_ = [1]struct{}{}[700-unsafe.Offsetof(Object{}.CollideData)]
	_ = [1]struct{}{}[732-unsafe.Offsetof(Object{}.Use)]
	_ = [1]struct{}{}[736-unsafe.Offsetof(Object{}.UseData)]
	_ = [1]struct{}{}[744-unsafe.Offsetof(Object{}.Update)]
	_ = [1]struct{}{}[748-unsafe.Offsetof(Object{}.UpdateData)]
	_ = [1]struct{}{}[760-unsafe.Offsetof(Object{}.ScriptVars)]
	_ = [1]struct{}{}[764-unsafe.Offsetof(Object{}.ScriptPickup)]
	_ = [1]struct{}{}[772-unsafe.Offsetof(Object{}.serverHandle)]
	_ = [1]struct{}{}[20-unsafe.Sizeof(ModifierInitData{})]
	_ = [1]struct{}{}[16-unsafe.Offsetof(ModifierInitData{}.Field16)]
	_ = [1]struct{}{}[88-unsafe.Sizeof(Modifier{})]
	_ = [1]struct{}{}[4-unsafe.Offsetof(Modifier{}.TypeInd)]
	_ = [1]struct{}{}[8-unsafe.Offsetof(Modifier{}.Desc8)]
	_ = [1]struct{}{}[60-unsafe.Offsetof(Modifier{}.ReqStrength60)]
	_ = [1]struct{}{}[64-unsafe.Offsetof(Modifier{}.DamageCoeffOrArmor64)]
	_ = [1]struct{}{}[72-unsafe.Offsetof(Modifier{}.DamageMin72)]
	_ = [1]struct{}{}[80-unsafe.Offsetof(Modifier{}.Next80)]
	_ = [1]struct{}{}[12-unsafe.Sizeof(ModifierEffFnc{})]
	_ = [1]struct{}{}[144-unsafe.Sizeof(ModifierEff{})]
	_ = [1]struct{}{}[8-unsafe.Offsetof(ModifierEff{}.desc8)]
	_ = [1]struct{}{}[12-unsafe.Offsetof(ModifierEff{}.secdesc12)]
	_ = [1]struct{}{}[16-unsafe.Offsetof(ModifierEff{}.identdesc16)]
	_ = [1]struct{}{}[100-unsafe.Offsetof(ModifierEff{}.Update100)]
	_ = [1]struct{}{}[136-unsafe.Offsetof(ModifierEff{}.next136)]
	_ = [1]struct{}{}[2200-unsafe.Sizeof(MonsterUpdateData{})]
	_ = [1]struct{}{}[376-unsafe.Offsetof(MonsterUpdateData{}.Direction94)]
	_ = [1]struct{}{}[380-unsafe.Offsetof(MonsterUpdateData{}.Pos95)]
	_ = [1]struct{}{}[412-unsafe.Offsetof(MonsterUpdateData{}.HealthGraph103)]
	_ = [1]struct{}{}[484-unsafe.Offsetof(MonsterUpdateData{}.MonsterDef)]
	_ = [1]struct{}{}[544-unsafe.Offsetof(MonsterUpdateData{}.AIStackInd)]
	_ = [1]struct{}{}[552-unsafe.Offsetof(MonsterUpdateData{}.AIStack)]
	_ = [1]struct{}{}[1272-unsafe.Offsetof(MonsterUpdateData{}.ScriptCollision)]
	_ = [1]struct{}{}[1304-unsafe.Offsetof(MonsterUpdateData{}.Aggression)]
	_ = [1]struct{}{}[1312-unsafe.Offsetof(MonsterUpdateData{}.SightRange)]
	_ = [1]struct{}{}[1328-unsafe.Offsetof(MonsterUpdateData{}.Field332)]
	_ = [1]struct{}{}[1332-unsafe.Offsetof(MonsterUpdateData{}.Field333)]
	_ = [1]struct{}{}[1352-unsafe.Offsetof(MonsterUpdateData{}.Field338)]
	_ = [1]struct{}{}[1356-unsafe.Offsetof(MonsterUpdateData{}.FleeRange)]
	_ = [1]struct{}{}[1360-unsafe.Offsetof(MonsterUpdateData{}.AIAction340)]
	_ = [1]struct{}{}[1440-unsafe.Offsetof(MonsterUpdateData{}.StatusFlags)]
	_ = [1]struct{}{}[2176-unsafe.Offsetof(MonsterUpdateData{}.BombCollideTarget)]
	_ = [1]struct{}{}[164-unsafe.Sizeof(MonsterGenUpdateData{})]
	_ = [1]struct{}{}[72-unsafe.Offsetof(MonsterGenUpdateData{}.ScriptCollision)]
	_ = [1]struct{}{}[24-unsafe.Sizeof(AIStackItem{})]
	_ = [1]struct{}{}[0-unsafe.Offsetof(AIStackItem{}.Action)]
	_ = [1]struct{}{}[4-unsafe.Offsetof(AIStackItem{}.Args)]
	_ = [1]struct{}{}[20-unsafe.Offsetof(AIStackItem{}.Field5)]
	_ = [1]struct{}{}[248-unsafe.Sizeof(MonsterDef{})]
	_ = [1]struct{}{}[112-unsafe.Offsetof(MonsterDef{}.MeleeAttackRange112)]
)
