package legacy

import (
	"fmt"
	"math"
	"reflect"
	"strings"
	"testing"
)

type questBriefingDrawFixture44F300 struct {
	trace                 []string
	fail                  int
	width, height         int32
	widths                map[string]int32
	frame, blink          uint32
	titleFont, normalFont int
	colors                [3]uint32
	cache                 [12]int
	result                int32
}

func newQuestBriefingDrawFixture44F300() *questBriefingDrawFixture44F300 {
	f := &questBriefingDrawFixture44F300{fail: -1, width: 640, height: 480,
		widths: map[string]int32{"1": 100}, frame: 1, blink: 1,
		titleFont: 77, normalFont: 88, colors: [3]uint32{256, 512, 768}, result: math.MinInt32 + 1}
	for i := range f.cache {
		f.cache[i] = i + 101
	}
	return f
}

func (f *questBriefingDrawFixture44F300) step(s string) {
	f.trace = append(f.trace, s)
	if len(f.trace)-1 == f.fail {
		panic("fixture fault")
	}
}

func (f *questBriefingDrawFixture44F300) hooks(t *testing.T) questBriefingDrawHooks44F300[int, int, int, string] {
	t.Helper()
	return questBriefingDrawHooks44F300[int, int, int, string]{
		viewport:       func() int { f.step("viewport"); return 999 },
		initPreviews:   func() { f.step("init") },
		resetParticles: func() { f.step("reset") },
		hideBook:       func(v int32) int32 { f.step(fmt.Sprintf("hide:%d", v)); return -1 },
		prepare:        func() { f.step("prepare") },
		dimensions:     func() (int32, int32) { f.step("dimensions"); return f.width, f.height },
		loadText: func(key, source string, line int32) string {
			if source != `C:\NoxPost\src\client\Gui\GUIBrief.c` {
				t.Fatalf("source=%q", source)
			}
			key = strings.TrimPrefix(key, "GeneralPrint:QuestSplash")
			f.step(fmt.Sprintf("text:%s:%d", key, line))
			return key
		},
		titleFont:  func() int { f.step("title-font"); return f.titleFont },
		normalFont: func() int { f.step("normal-font"); return f.normalFont },
		measure: func(font int, text string) int32 {
			f.step(fmt.Sprintf("measure:%d:%s", font, text))
			if w, ok := f.widths[text]; ok {
				return w
			}
			return 10
		},
		color:    func(c questBriefingColor44F300) uint32 { f.step(fmt.Sprintf("color-load:%d", c)); return f.colors[c] },
		setColor: func(c uint32) { f.step(fmt.Sprintf("color:%d", c)) },
		drawText: func(font int, text string, x, y int32) int32 {
			f.step(fmt.Sprintf("draw:%d:%s:%d:%d", font, text, x, y))
			return f.result
		},
		wrapText: func(font int, text string, x, y, w, h int32) int32 {
			f.step(fmt.Sprintf("wrap:%d:%s:%d:%d:%d:%d", font, text, x, y, w, h))
			return f.result
		},
		loadDrawable: func(slot int) int { f.step(fmt.Sprintf("load-icon:%d", slot)); return f.cache[slot] },
		position:     func(vp, dr int, x, y int32) { f.step(fmt.Sprintf("position:%d:%d:%d:%d", vp, dr, x, y)) },
		drawDrawable: func(vp, dr int) { f.step(fmt.Sprintf("icon:%d:%d", vp, dr)) },
		frame:        func() uint32 { f.step("frame"); return f.frame },
		loadBlink:    func() uint32 { f.step("blink-load"); return f.blink },
		storeBlink:   func(v uint32) { f.step(fmt.Sprintf("blink-store:%d", v)); f.blink = v },
	}
}

// Independently transcribed call sequence and absolute 640x480 coordinates
// from the sealed x86 instructions, not generated by the ported layout.
func questBriefingDrawGolden44F300() []string {
	out := []string{"viewport", "init", "reset", "hide:1", "prepare", "dimensions",
		"text:1:765", "title-font", "measure:77:1", "color-load:0", "color:256"}
	titleDraw := func(key string, x, y int32) {
		out = append(out, "title-font", fmt.Sprintf("draw:77:%s:%d:%d", key, x, y))
	}
	col := func(i int) { out = append(out, fmt.Sprintf("color-load:%d", i), fmt.Sprintf("color:%d", (i+1)*256)) }
	txt := func(key string, line int) { out = append(out, fmt.Sprintf("text:%s:%d", key, line)) }
	measure := func(key string) { out = append(out, "normal-font", "measure:88:"+key) }
	draw := func(key string, x, y int32) {
		out = append(out, "normal-font", fmt.Sprintf("draw:88:%s:%d:%d", key, x, y))
	}
	wrap := func(key string, x, y, w int32) {
		out = append(out, "normal-font", fmt.Sprintf("wrap:88:%s:%d:%d:%d:0", key, x, y, w))
	}
	icon := func(slot int, x, y int32) {
		out = append(out, fmt.Sprintf("load-icon:%d", slot), fmt.Sprintf("position:999:%d:%d:%d", slot+101, x, y),
			fmt.Sprintf("load-icon:%d", slot), fmt.Sprintf("icon:999:%d", slot+101))
	}
	titleDraw("1", 269, 19)
	titleDraw("1", 271, 19)
	titleDraw("1", 269, 21)
	titleDraw("1", 271, 21)
	col(1)
	titleDraw("1", 270, 20)
	icon(0, 73, 123)
	txt("2a", 792)
	col(1)
	draw("2a", 109, 76)
	measure("2a")
	col(2)
	txt("2b", 799)
	wrap("2b", 123, 76, 397)
	icon(1, 565, 117)
	txt("3a", 809)
	measure("3a")
	txt("3b", 811)
	measure("3b")
	col(1)
	draw("3a", 496, 115)
	col(2)
	draw("3b", 510, 115)
	icon(3, 133, 192)
	txt("4a", 862)
	col(1)
	draw("4a", 157, 156)
	measure("4a")
	col(2)
	txt("4b", 869)
	wrap("4b", 171, 156, 459)
	icon(2, 525, 222)
	txt("7a", 879)
	measure("7a")
	txt("7b", 881)
	measure("7b")
	col(1)
	draw("7a", 476, 198)
	col(2)
	draw("7b", 490, 198)
	icon(9, 182, 262)
	icon(11, 201, 251)
	icon(10, 185, 234)
	txt("5a", 942)
	col(1)
	draw("5a", 221, 240)
	measure("5a")
	col(2)
	txt("5b", 949)
	wrap("5b", 235, 240, 235)
	icon(6, 484, 278)
	icon(7, 503, 303)
	txt("6a", 964)
	measure("6a")
	txt("6b", 966)
	measure("6b")
	col(1)
	draw("6a", 438, 286)
	col(2)
	draw("6b", 452, 286)
	icon(5, 186, 333)
	icon(4, 219, 345)
	icon(8, 220, 322)
	txt("8a", 1027)
	col(1)
	draw("8a", 241, 330)
	measure("8a")
	col(2)
	txt("8b", 1034)
	wrap("8b", 255, 330, 295)
	txt("9a", 1040)
	txt("9b", 1041)
	measure("9a")
	measure("9b")
	col(1)
	draw("9a", 310, 370)
	col(2)
	draw("9b", 324, 370)
	txt("10a", 1055)
	txt("10b", 1056)
	measure("10a")
	measure("10b")
	col(1)
	draw("10a", 310, 395)
	col(2)
	draw("10b", 324, 395)
	txt("11a", 1070)
	txt("11b", 1071)
	measure("11a")
	measure("11b")
	col(1)
	draw("11a", 310, 420)
	col(2)
	draw("11b", 324, 420)
	out = append(out, "frame", "blink-load", "color-load:2", "text:12:1097", "normal-font", "measure:88:12", "color:768")
	titleDraw("12", 315, 450)
	return out
}

func TestQuestBriefingDraw44F300CompleteGoldenTrace(t *testing.T) {
	f := newQuestBriefingDrawFixture44F300()
	if got := questBriefingDraw44F300(f.hooks(t)); got != math.MinInt32+1 {
		t.Fatalf("return=%d", got)
	}
	want := questBriefingDrawGolden44F300()
	if !reflect.DeepEqual(f.trace, want) {
		for i := range min(len(f.trace), len(want)) {
			if f.trace[i] != want[i] {
				t.Fatalf("first difference %d: %q want %q", i, f.trace[i], want[i])
			}
		}
		t.Fatalf("trace lengths %d/%d", len(f.trace), len(want))
	}
}

func TestQuestBriefingDraw44F300BranchBoundariesAndDwordArithmetic(t *testing.T) {
	for _, pair := range []struct {
		a, b                  string
		limit, right, left, y int32
	}{
		{"3a", "3b", 390, 520, 199, 115}, {"7a", "7b", 215, 500, 250, 198}, {"6a", "6b", 350, 462, 113, 286},
	} {
		for _, aw := range []int32{pair.limit - 10, pair.limit - 9, -100, math.MaxInt32} {
			t.Run(fmt.Sprintf("%s/%d", pair.a, aw), func(t *testing.T) {
				f := newQuestBriefingDrawFixture44F300()
				f.widths[pair.a], f.widths[pair.b] = aw, 10
				questBriefingDraw44F300(f.hooks(t))
				var aWant, bWant string
				if int64(aw)+10 > math.MaxInt32 || aw+10 <= pair.limit {
					aWant = fmt.Sprintf("draw:88:%s:%d:%d", pair.a, pair.right-10-aw-4, pair.y)
					bWant = fmt.Sprintf("draw:88:%s:%d:%d", pair.b, pair.right-10, pair.y)
				} else {
					x := pair.left + aw + 4
					aWant = fmt.Sprintf("draw:88:%s:%d:%d", pair.a, pair.left, pair.y)
					bWant = fmt.Sprintf("wrap:88:%s:%d:%d:%d:0", pair.b, x, pair.y, pair.right-x)
				}
				if !containsQuestTrace44F300(f.trace, aWant) || !containsQuestTrace44F300(f.trace, bWant) {
					t.Fatalf("missing %q/%q in %v", aWant, bWant, f.trace)
				}
			})
		}
	}
	for _, wh := range [][2]int32{{639, 479}, {-1, -1}, {math.MinInt32, math.MaxInt32}, {math.MaxInt32, math.MinInt32}, {1920, 1080}} {
		f := newQuestBriefingDrawFixture44F300()
		f.width, f.height = wh[0], wh[1]
		f.widths["1"], f.widths["9a"], f.widths["9b"] = math.MinInt32, math.MaxInt32, 10
		questBriefingDraw44F300(f.hooks(t))
		dx, dy := (wh[0]-640)/2, (wh[1]-480)/2
		sum := int32(math.MaxInt32)
		sum += 10
		for _, event := range []string{
			fmt.Sprintf("draw:77:1:%d:%d", dx-int32(math.MinInt32)/2+320, dy+20),
			fmt.Sprintf("position:999:101:%d:%d", dx+73, dy+123),
			fmt.Sprintf("wrap:88:4b:%d:%d:%d:0", dx+171, dy+156, dy-(dx+171)+630),
			fmt.Sprintf("draw:88:9a:%d:%d", dx-sum/2+320, dy+370),
		} {
			if !containsQuestTrace44F300(f.trace, event) {
				t.Fatalf("missing %q in %v", event, f.trace)
			}
		}
	}
}

func containsQuestTrace44F300(trace []string, s string) bool {
	for _, event := range trace {
		if event == s {
			return true
		}
	}
	return false
}

func TestQuestBriefingDraw44F300BlinkReturnAndSingleFrameLoad(t *testing.T) {
	for _, frame := range []uint32{0, 1, 29, 30, 31, 60, math.MaxUint32 - 15, math.MaxUint32} {
		for _, blink := range []uint32{0, 1, 2, math.MaxUint32} {
			f := newQuestBriefingDrawFixture44F300()
			f.frame, f.blink = frame, blink
			h := f.hooks(t)
			frameHook := h.frame
			frameLoads := 0
			h.frame = func() uint32 { frameLoads++; v := frameHook(); f.frame++; return v }
			got := questBriefingDraw44F300(h)
			wantBlink, wantRet, wantPrompt := blink, int32(frame/30), blink == 1
			if frame%30 == 0 {
				if blink == 1 {
					wantBlink, wantRet, wantPrompt = 0, 1, false
				} else {
					wantBlink, wantPrompt = 1, true
				}
			}
			if wantPrompt {
				wantRet = f.result
			}
			if got != wantRet || f.blink != wantBlink || frameLoads != 1 || containsQuestTrace44F300(f.trace, "text:12:1097") != wantPrompt {
				t.Fatalf("frame=%d blink=%d return=%d/%d newBlink=%d/%d loads=%d trace=%v", frame, blink, got, wantRet, f.blink, wantBlink, frameLoads, f.trace)
			}
		}
	}
}

func TestQuestBriefingDraw44F300EveryFaultPrefix(t *testing.T) {
	for _, overflow := range []bool{false, true} {
		for _, blink := range []uint32{0, 1, 2} {
			base := newQuestBriefingDrawFixture44F300()
			base.frame, base.blink = 30, blink
			if overflow {
				base.widths["3a"], base.widths["7a"], base.widths["6a"] = 500, 500, 500
			}
			questBriefingDraw44F300(base.hooks(t))
			want := base.trace
			for n := range want {
				f := newQuestBriefingDrawFixture44F300()
				f.frame, f.blink, f.fail = 30, blink, n
				if overflow {
					f.widths["3a"], f.widths["7a"], f.widths["6a"] = 500, 500, 500
				}
				var caught any
				func() { defer func() { caught = recover() }(); questBriefingDraw44F300(f.hooks(t)) }()
				if caught != "fixture fault" || !reflect.DeepEqual(f.trace, want[:n+1]) {
					t.Fatalf("overflow=%v blink=%d fault=%d caught=%v trace=%v want=%v", overflow, blink, n, caught, f.trace, want[:n+1])
				}
			}
		}
	}
}

func TestQuestBriefingDraw44F300LiveFontCacheAndCachedPromptColor(t *testing.T) {
	f := newQuestBriefingDrawFixture44F300()
	h := f.hooks(t)
	draw, measure, position, load := h.drawText, h.measure, h.position, h.loadText
	h.drawText = func(font int, text string, x, y int32) int32 {
		v := draw(font, text, x, y)
		if text == "1" {
			f.titleFont++
		}
		return v
	}
	h.measure = func(font int, text string) int32 {
		v := measure(font, text)
		if text == "2a" {
			f.normalFont = 909
		}
		return v
	}
	h.position = func(vp, dr int, x, y int32) {
		position(vp, dr, x, y)
		if dr == 101 {
			f.cache[0] = 1001
		}
	}
	h.loadText = func(key, source string, line int32) string {
		v := load(key, source, line)
		if line == 1097 {
			f.colors[2] = 0xdeadbeef
			f.titleFont = 515
		}
		return v
	}
	questBriefingDraw44F300(h)
	for _, event := range []string{"draw:77:1:269:19", "draw:78:1:271:19", "draw:81:1:270:20",
		"icon:999:1001", "wrap:909:2b:123:76:397:0", "color:768", "measure:909:12", "draw:515:12:315:450"} {
		if !containsQuestTrace44F300(f.trace, event) {
			t.Fatalf("missing %q in %v", event, f.trace)
		}
	}
	if containsQuestTrace44F300(f.trace, "color:3735928559") {
		t.Fatal("prompt reloaded the white color after lookup")
	}
}
