#ifndef NOX_PORT_SPELL_DURATION_FREE_RECURSIVE_4FE980_H
#define NOX_PORT_SPELL_DURATION_FREE_RECURSIVE_4FE980_H

void sub_4FE980(void* record);

#endif // NOX_PORT_SPELL_DURATION_FREE_RECURSIVE_4FE980_H
