#ifndef NOX_PORT_SPELL_DURATION_SELECTIVE_CLEANUP_4FE8A0_H
#define NOX_PORT_SPELL_DURATION_SELECTIVE_CLEANUP_4FE8A0_H

#include <stdint.h>

void sub_4FE8A0(int32_t mode);

#endif // NOX_PORT_SPELL_DURATION_SELECTIVE_CLEANUP_4FE8A0_H
